csiHostpathPlugin:
  pluginRegistrationDir: /var/snap/microk8s/common/var/lib/kubelet/plugins_registry

csiHostpathProvisioner:
  topologyEnabled: false


   # TODO: parameterize (customize by build, microk8s vs other)